syntax on

set background=light "this is only for Mac with light colorscheme

set expandtab "Insert spaces instead of <TAB> character when the <TAB> key is pressed.       
set textwidth=120    
set tabstop=4    
set softtabstop=4
set shiftwidth=4    
set autoindent "the indent of the new line will match that of the previous line.

set backspace=indent,eol,start
set number
set ruler    
set showcmd   
